### ISSUE TITLE
time check

### ISSUE THREAD

**Issue by ajrominger** [hawaiiDimensions/db#3]
check everything is in correct format

**Comment by eghuang** [comment]
We need to check if the current time function is working and also add method-contingent time format checking functions.

For example, columns TimeBegin, TimeEnd, and DateEnd are required for some but not all methods.
We need to check that these columns are correctly formatted for samples that have the related collection methods.

**Comment by ajrominger** [comment]
Valid range for collection dates: March 1, 2014 to January 1, 2016.  Format should be %m/%d/YYYY (e.g. 7/8/2015 or 07/08/2015 are both valid, but 7/8/15 would not be valid).

TimeBegin and TimeEnd should be in 24hr time (i.e. military time)
